export const CARDS = [
  {
    source: "DUBAI",
    destination: "SINGAPORE",
    date: "15 Apr 2025",
    arrival_time: "06:45 PM",
    departure_time: "02:30 PM",
    qr_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/QR_code_for_mobile_English_Wikipedia.svg/1920px-QR_code_for_mobile_English_Wikipedia.svg.png",
    meta: [
      { title: "flight", subtitle: "EK353" },
      { title: "seat no", subtitle: "12A" },
      { title: "gate", subtitle: "B12" },
      { title: "pnr", subtitle: "DXB789" },
    ],
  },
  {
    source: "MUMBAI",
    destination: "BANGALORE",
    date: "22 May 2025",
    arrival_time: "09:20 PM",
    departure_time: "07:15 PM",
    qr_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/QR_code_for_mobile_English_Wikipedia.svg/1920px-QR_code_for_mobile_English_Wikipedia.svg.png",
    meta: [
      { title: "flight", subtitle: "6E234" },
      { title: "seat no", subtitle: "8C" },
      { title: "gate", subtitle: "A5" },
      { title: "pnr", subtitle: "MUM456" },
    ],
  },
  {
    source: "NEW YORK",
    destination: "TOKYO",
    date: "10 Jun 2025",
    arrival_time: "04:00 PM",
    departure_time: "11:30 AM",
    qr_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/QR_code_for_mobile_English_Wikipedia.svg/1920px-QR_code_for_mobile_English_Wikipedia.svg.png",
    meta: [
      { title: "flight", subtitle: "UA837" },
      { title: "seat no", subtitle: "24F" },
      { title: "gate", subtitle: "C22" },
      { title: "pnr", subtitle: "JFK123" },
    ],
  },
  {
    source: "LONDON",
    destination: "PARIS",
    date: "28 Jul 2025",
    arrival_time: "10:45 AM",
    departure_time: "09:00 AM",
    qr_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/QR_code_for_mobile_English_Wikipedia.svg/1920px-QR_code_for_mobile_English_Wikipedia.svg.png",
    meta: [
      { title: "flight", subtitle: "BA304" },
      { title: "seat no", subtitle: "15B" },
      { title: "gate", subtitle: "D8" },
      { title: "pnr", subtitle: "LHR999" },
    ],
  },
];
